# Generated by Django 3.2.9 on 2022-08-13 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 13, 23, 42, 39, 175362)),
        ),
    ]
